### ISSUE TITLE
ADDME for required args only

### ISSUE THREAD

**Issue by bendichter** [rly/buffalo-lab-data-to-nwb#22]
in the metadata.yml, experiment_description and session_id are both listed with ADDME despite the fact that they are not required args.

https://github.com/ben-dichter-consulting/buffalo-lab-data-to-nwb/blob/b66970f1560a7c4a8dbd79eec56e2244408035f5/src/buffalonwb/metafile.yml#L23

Could we change this to only use ADDME when an arg is required?

**Comment by luiztauffer** [comment]
sure!
